services:
  db:
    image: postgres:15-alpine
    container_name: daangn-db
    environment:
      POSTGRES_USER: daangn
      POSTGRES_PASSWORD: daangn1951
      POSTGRES_DB: daangndb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - daangn-network

  redis:
    image: redis:7-alpine
    container_name: daangn-redis
    ports:
      - "6379:6379"
    networks:
      - daangn-network

networks:
  daangn-network:
    driver: bridge

volumes:
  postgres_data: